### ISSUE TITLE
Missing DESCRIPTION.rst

### ISSUE THREAD

**Issue by jabalazs** [RealTimeWeb/datasets#134]
Hi, thanks for taking the time for putting this together!
I was trying to install this package through pip and got the following error:

```
$ pip install datasets                                                                                                          
Collecting datasets
  Downloading datasets-0.0.9.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-pwDayg/datasets/setup.py", line 10, in <module>
        with open(path.join(here, 'DESCRIPTION.rst'), encoding='utf-8') as f:
      File "/home/jabalazs/Envs/test/lib/python2.7/codecs.py", line 896, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-pwDayg/datasets/DESCRIPTION.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-pwDayg/datasets/
```
Googling a bit I came upon this solution https://stackoverflow.com/a/38165113/3941813 in which they suggest to directly download the package from Pypi ([here](https://pypi.python.org/pypi/datasets/0.0.9)), remove the lines dealing with DESCRIPTION.rst in setup.py, and install it by running `python setup.py install`

Doing so executes the setup script successfully.

Is there a way to fix this during the build process, before publishing the package to Pypi?

**Comment by acbart** [comment]
Boy, I'm way behind on clearing up my email, this is from September. Sorry about that! The lurking issue that addresses both of your questions is that the CORGIS dataset collection isn't meant to be pip installable, but is a collection of datasets. Typically, you would download one of the libraries or datasets off a site, and then work with them in an academic environment. I suppose it could be pip installable, but you'd get the entire collection (which would be pretty big). I would think most people would only want the specific datasets they need for the class, except for developers interested in extending the datasets.

**Comment by joelachance** [comment]
This still seems to be an issue-- would it make sense to pull this off of pypi @acbart?

**Comment by acbart** [comment]
Eventually, we want to get it pip installable. That is a goal for the project, I just don't have the time to do so right now.
